// <auto-generated />
namespace PracticeTime.Web.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class C_Badge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(C_Badge));
        
        string IMigrationMetadata.Id
        {
            get { return "201402021723007_C_Badge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
